name: mini_blog
description: Mini blog de notas con backend FastAPI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
